<?php

return [
    'brands' => [
        'Acura' => ['ILX', 'MDX', 'RDX', 'TLX'],
        'Alfa Romeo' => ['159', 'Giulia', 'Giulietta', 'Stelvio', 'Tonale'],
        'Audi' => ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8'],
        'BMW' => ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', 'X1', 'X3', 'X4', 'X5', 'X6', 'X7'],
        'Chevrolet' => ['Aveo', 'Camaro', 'Captiva', 'Cruze', 'Lacetti', 'Malibu', 'Orlando', 'Tahoe'],
        'Chrysler' => ['200', '300', 'Pacifica', 'Voyager'],
        'Citroen' => ['Berlingo', 'C3', 'C4', 'C4 Picasso', 'C5 Aircross', 'Jumpy'],
        'Cupra' => ['Ateca', 'Born', 'Formentor', 'Leon'],
        'Dacia' => ['Duster', 'Jogger', 'Logan', 'Lodgy', 'Sandero'],
        'Daewoo' => ['Lanos', 'Nexia', 'Matiz'],
        'Dodge' => ['Challenger', 'Charger', 'Durango', 'Journey', 'RAM'],
        'Fiat' => ['500', '500L', 'Doblo', 'Ducato', 'Panda', 'Tipo'],
        'Ford' => ['EcoSport', 'Fiesta', 'Focus', 'Fusion', 'Kuga', 'Mondeo', 'Mustang', 'Ranger', 'Transit'],
        'Genesis' => ['G70', 'G80', 'GV70', 'GV80'],
        'Honda' => ['Accord', 'Civic', 'CR-V', 'HR-V', 'Jazz', 'Pilot'],
        'Hyundai' => ['Accent', 'Elantra', 'Getz', 'i30', 'Kona', 'Santa Fe', 'Sonata', 'Tucson'],
        'Infiniti' => ['EX', 'FX', 'Q50', 'Q60', 'QX50', 'QX60', 'QX70'],
        'Isuzu' => ['D-Max', 'MU-X'],
        'Jaguar' => ['E-Pace', 'F-Pace', 'F-Type', 'XE', 'XF', 'XJ'],
        'Jeep' => ['Cherokee', 'Compass', 'Grand Cherokee', 'Patriot', 'Renegade', 'Wrangler'],
        'Kia' => ['Carens', 'Ceed', 'Cerato', 'Optima', 'Picanto', 'Rio', 'Sorento', 'Soul', 'Sportage', 'Stinger'],
        'Land Rover' => ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport'],
        'Lexus' => ['ES', 'GS', 'GX', 'IS', 'LX', 'NX', 'RX', 'UX'],
        'Mazda' => ['CX-3', 'CX-5', 'CX-7', 'CX-9', 'Mazda 2', 'Mazda 3', 'Mazda 6'],
        'Mercedes-Benz' => ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLC', 'GLE', 'GLS', 'S-Class', 'Sprinter', 'Vito'],
        'Mini' => ['Clubman', 'Cooper', 'Countryman', 'Paceman'],
        'Mitsubishi' => ['ASX', 'Eclipse Cross', 'L200', 'Lancer', 'Outlander', 'Pajero'],
        'Nissan' => ['Almera', 'Juke', 'Leaf', 'Micra', 'Navara', 'Note', 'Qashqai', 'Rogue', 'X-Trail'],
        'Opel' => ['Astra', 'Combo', 'Corsa', 'Crossland', 'Insignia', 'Meriva', 'Mokka', 'Vectra', 'Vivaro', 'Zafira'],
        'Peugeot' => ['2008', '206', '207', '208', '3008', '301', '308', '408', '5008', 'Partner'],
        'Porsche' => ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera'],
        'Renault' => ['Clio', 'Dokker', 'Duster', 'Kangoo', 'Kaptur', 'Logan', 'Megane', 'Sandero', 'Scenic', 'Trafic'],
        'Seat' => ['Alhambra', 'Arona', 'Ateca', 'Ibiza', 'Leon', 'Toledo'],
        'Skoda' => ['Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Roomster', 'Superb', 'Yeti'],
        'Subaru' => ['Forester', 'Impreza', 'Legacy', 'Outback', 'Tribeca', 'XV'],
        'Suzuki' => ['Grand Vitara', 'Jimny', 'S-Cross', 'Swift', 'SX4', 'Vitara'],
        'Tesla' => ['Model 3', 'Model S', 'Model X', 'Model Y'],
        'Toyota' => ['Auris', 'Avensis', 'Camry', 'Corolla', 'Highlander', 'Hilux', 'Land Cruiser', 'Prado', 'Prius', 'RAV4', 'Yaris'],
        'Volkswagen' => ['Amarok', 'Arteon', 'Caddy', 'Crafter', 'Golf', 'Jetta', 'Passat', 'Polo', 'Sharan', 'T-Cross', 'Tiguan', 'Touareg', 'Transporter'],
        'Volvo' => ['S40', 'S60', 'S80', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'],
    ],
];
